#!/bin/sh
# Uses xwinwrap to display given animated .gif in the center of the screen

if [ $# -ne 1 ]; then
    echo 1>&2 Usage: $0 image.gif
    exit 1
fi

#get screen resolution
SCRW=`xrandr | awk '/current/ { print $8 }'`
SCRH=`xrandr | awk '/current/ { print $10 }'`
SCRH=${SCRH%\,}

#get gif resolution
#IMGHW=`gifsicle --info $1 | awk '/logical/ { print $3 }'`
#IMGH=${IMGHW%x*}
#IMGW=${IMGHW#*x}

#calculate position
#POSH=$((($SCRH/2)-($IMGH/2)))
#POSW=$((($SCRW/2)-($IMGW/2)))
#echo $SCRW
#echo $SCRH
#${SCRH}x${SCRW}+0+0
xwinwrap -ov -g 1920x1080+0+0 -- mpv -wid WID $1 --no-osc --no-osd-bar --loop-file --player-operation-mode=cplayer --no-audio --panscan=1.0 --no-input-default-bindings

#xwinwrap -g ${IMGHW}+${POSH}+${POSW} -ov -ni -s -nf -- gifview -w WID $1 -a


exit 0
